/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      "colors": {
        "secondary-fixed": "#c0e8ff",
        "on-tertiary": "#ffffff",
        "on-primary-fixed-variant": "#004c6e",
        "surface-dim": "#d2d9f4",
        "secondary-container": "#7ed4fd",
        "on-error-container": "#93000a",
        "tertiary-fixed-dim": "#bfc8ce",
        "primary-fixed": "#c9e6ff",
        "surface-container-lowest": "#ffffff",
        "surface-bright": "#faf8ff",
        "outline-variant": "#bec8d2",
        "on-background": "#131b2e",
        "on-primary-fixed": "#001e2f",
        "surface-variant": "#dae2fd",
        "surface-container-highest": "#dae2fd",
        "on-primary-container": "#003751",
        "background": "#faf8ff",
        "tertiary-fixed": "#dbe4ea",
        "error": "#ba1a1a",
        "inverse-surface": "#283044",
        "surface-container-high": "#e2e7ff",
        "surface-container": "#eaedff",
        "surface-container-low": "#f2f3ff",
        "on-primary": "#ffffff",
        "on-error": "#ffffff",
        "on-tertiary-container": "#2c3539",
        "secondary-fixed-dim": "#7bd1fa",
        "primary-fixed-dim": "#89ceff",
        "on-secondary-fixed-variant": "#004d66",
        "on-secondary-fixed": "#001e2b",
        "outline": "#6e7881",
        "inverse-primary": "#89ceff",
        "surface-tint": "#006591",
        "on-tertiary-fixed": "#141d21",
        "tertiary-container": "#949da3",
        "primary": "#006591",
        "tertiary": "#576065",
        "inverse-on-surface": "#eef0ff",
        "on-tertiary-fixed-variant": "#3f484d",
        "on-secondary": "#ffffff",
        "secondary": "#006686",
        "primary-container": "#0ea5e9",
        "on-surface": "#131b2e",
        "on-secondary-container": "#005b78",
        "surface": "#faf8ff",
        "on-surface-variant": "#3e4850",
        "error-container": "#ffdad6"
      },
      "borderRadius": {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      "spacing": {
        "base": "4px",
        "sm": "16px",
        "xs": "8px",
        "md": "24px",
        "xl": "80px",
        "lg": "48px",
        "margin": "32px",
        "gutter": "24px",
        "margin-mobile": "20px",
        "margin-desktop": "64px",
        "container-max": "1280px",
        "stack-sm": "8px",
        "stack-md": "24px",
        "stack-lg": "48px"
      },
      "fontFamily": {
        "headline-md": ["Ranchers", "sans-serif"],
        "headline-lg-mobile": ["Ranchers", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-lg": ["Ranchers", "sans-serif"],
        "display-lg": ["Ranchers", "sans-serif"],
        "display-lg-mobile": ["Ranchers", "sans-serif"],
        "label-caps": ["Ranchers", "sans-serif"],
        "button": ["Ranchers", "sans-serif"]
      },
      "fontSize": {
        "headline-md": ["24px", { "lineHeight": "32px", "fontWeight": "600" }],
        "headline-lg-mobile": ["28px", { "lineHeight": "36px", "fontWeight": "700" }],
        "label-sm": ["12px", { "lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "500" }],
        "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }],
        "headline-lg": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "700" }],
        "display-lg": ["48px", { "lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "800" }],
        "display-lg-mobile": ["48px", { "lineHeight": "1.1", "letterSpacing": "-0.04em", "fontWeight": "800" }],
        "label-caps": ["12px", { "lineHeight": "1.0", "letterSpacing": "0.1em", "fontWeight": "500" }],
        "button": ["14px", { "lineHeight": "1.0", "letterSpacing": "0.02em", "fontWeight": "700" }]
      },
      keyframes: {
        shine: {
          '0%': { transform: 'translateX(-200%) skewX(-12deg)' },
          '100%': { transform: 'translateX(200%) skewX(-12deg)' },
        }
      },
      animation: {
        shine: 'shine 2s infinite linear'
      }
    },
  },
  plugins: [],
}
