-- Migration: Booking Delete Password Security
-- Description: Creates a secure, separate admin password mechanism specifically for destructive actions like booking deletion.
-- Uses pgcrypto to ensure passwords are never stored in plaintext and never leave the database.

-- 1. Ensure pgcrypto is enabled
CREATE EXTENSION IF NOT EXISTS pgcrypto WITH SCHEMA extensions;

-- 2. Create the admin security table
CREATE TABLE IF NOT EXISTS public.admin_security (
    id uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    booking_delete_password_hash text NOT NULL,
    updated_at timestamptz DEFAULT now()
);

-- Enable RLS
ALTER TABLE public.admin_security ENABLE ROW LEVEL SECURITY;

-- Admins can only manage their own security row (or we allow it via Security Definer RPCs)
CREATE POLICY "Admins can manage their own security" ON public.admin_security
    FOR ALL
    TO authenticated
    USING (auth.uid() = id AND public.is_admin());

-- 3. RPC to Set or Update the Delete Password
CREATE OR REPLACE FUNCTION public.set_booking_delete_password(p_password text)
RETURNS void AS $$
BEGIN
    -- Verify the caller is an admin
    IF NOT public.is_admin() THEN
        RAISE EXCEPTION 'Not authorized';
    END IF;

    -- Store the hashed password
    INSERT INTO public.admin_security (id, booking_delete_password_hash, updated_at)
    VALUES (
        auth.uid(),
        extensions.crypt(p_password, extensions.gen_salt('bf')),
        now()
    )
    ON CONFLICT (id) DO UPDATE SET 
        booking_delete_password_hash = extensions.crypt(p_password, extensions.gen_salt('bf')),
        updated_at = now();
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- 4. RPC to Verify the Delete Password
CREATE OR REPLACE FUNCTION public.verify_booking_delete_password(p_admin_id uuid, p_password text)
RETURNS boolean AS $$
DECLARE
    v_hash text;
BEGIN
    -- Fetch the stored hash
    SELECT booking_delete_password_hash INTO v_hash
    FROM public.admin_security
    WHERE id = p_admin_id;

    -- If no hash is found, they haven't configured a password yet
    IF v_hash IS NULL THEN
        RETURN false;
    END IF;

    -- Verify the password
    RETURN v_hash = extensions.crypt(p_password, v_hash);
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- 5. RPC to Check if Delete Password is Configured
CREATE OR REPLACE FUNCTION public.has_booking_delete_password()
RETURNS boolean AS $$
DECLARE
    v_exists boolean;
BEGIN
    SELECT EXISTS (
        SELECT 1 FROM public.admin_security WHERE id = auth.uid()
    ) INTO v_exists;
    
    RETURN v_exists;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Note: Password reset links (token-based) should be generated by an edge function or handled via standard secure flows. 
-- However, for the scope of the immediate UI "Forgot password" flow, sending a short-lived token to the admin's email can be managed by a separate table if needed.

-- 6. Booking Delete Reset Tokens Table
CREATE TABLE IF NOT EXISTS public.admin_security_reset_tokens (
    token_id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    admin_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    token_hash text NOT NULL,
    expires_at timestamptz NOT NULL,
    used boolean DEFAULT false,
    created_at timestamptz DEFAULT now()
);

ALTER TABLE public.admin_security_reset_tokens ENABLE ROW LEVEL SECURITY;

-- Deny direct access. Only accessed via Security Definer RPCs or Service Role.
CREATE POLICY "No direct access to reset tokens" ON public.admin_security_reset_tokens FOR ALL TO public USING (false);

-- 7. RPC to generate reset token (called via Edge Function, or returns to Edge Function)
-- The Edge Function will generate a random string, hash it, store the hash here, and email the plaintext token.
CREATE OR REPLACE FUNCTION public.create_booking_delete_reset_token(p_admin_id uuid, p_token_hash text, p_expiry_minutes integer)
RETURNS void AS $$
BEGIN
    INSERT INTO public.admin_security_reset_tokens (admin_id, token_hash, expires_at)
    VALUES (p_admin_id, p_token_hash, now() + (p_expiry_minutes || ' minutes')::interval);
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- 8. RPC to use reset token and set new password
CREATE OR REPLACE FUNCTION public.reset_booking_delete_password(p_admin_id uuid, p_token_hash text, p_new_password text)
RETURNS boolean AS $$
DECLARE
    v_token_id uuid;
BEGIN
    -- Find valid token
    SELECT token_id INTO v_token_id
    FROM public.admin_security_reset_tokens
    WHERE admin_id = p_admin_id 
      AND token_hash = p_token_hash
      AND used = false
      AND expires_at > now()
    LIMIT 1;

    IF v_token_id IS NULL THEN
        RETURN false;
    END IF;

    -- Mark token as used
    UPDATE public.admin_security_reset_tokens SET used = true WHERE token_id = v_token_id;

    -- Update password
    INSERT INTO public.admin_security (id, booking_delete_password_hash, updated_at)
    VALUES (p_admin_id, extensions.crypt(p_new_password, extensions.gen_salt('bf')), now())
    ON CONFLICT (id) DO UPDATE SET 
        booking_delete_password_hash = extensions.crypt(p_new_password, extensions.gen_salt('bf')),
        updated_at = now();

    RETURN true;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;
